version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: menucard-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - LIVE_MONGODB_URI=mongodb://mongodb:27017/menucard
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
