name: EC2 Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ububtu-latest

        env:
            EC2_HOST: 54.196.105.239

        steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Setup SSH Key
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.MY_EC2_KEYS }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

        - name: Add EC2 to Known Host
          run: |
            ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
  
        - name: Clone GitHub Repo
          run: git clone https://github.com/chikadevops/MENUCARD-AUTH-SERVICE.git

        - name: Setup .env File
          run: |
            echo "${{ secrets.ENV }}" > MENUCARD-AUTH-SERVICE/.env

        - name: Install Dependencies
          run: npm ci

        - name: Install Jest
          run: npm install --save-dev jest
        
        - name: Run Tests
          run: npm test

        - name: Run App
          run: npm run dev
