name: EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: 3.92.244.41

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MY_EC2_KEYS }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to Known Hosts
      run: |
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

    - name:  Copy .env File & Run Shell Script
      run: |
        ssh ubuntu@$EC2_HOST << 'EOF'
            docker stop mongodb-container || true
            docker rm mongodb-container || true
            docker run --name mongodb-container -d -p 27017:27017 mongo
            # Clone or update repo
            if [ -d "MENUCARD-AUTH-SERVICE" ]; then
                cd MENUCARD-AUTH-SERVICE && git pull
            else
                git clone https://github.com/chikadevops/MENUCARD-AUTH-SERVICE.git
            fi
            echo "${{ secrets.ENV }}" >  MENUCARD-AUTH-SERVICE/.env
            cd MENUCARD-AUTH-SERVICE && chmod +x deploy.sh
            ./deploy.sh
        EOF
